version: '3'
services:

  postgres:
    image: postgres:latest
    volumes:
      - ./db/sql/db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: 'vision'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  redis:
    image: "redis:6.2.6"

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
      - "6379:6379"
