name: diagrams-svg-pfg
on:
  push:
    branches:
      - master

jobs:
  pdf:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: DrawIO CLI
          run: apt install snapd && \
               snap install drawio
