name: diagrams-svg-pfg
on:
  push:
    branches:
      - master

jobs:
  pdf:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Convert test file to jpeg image
          uses: ./
          with:
            quality: 100
            scale: 1.0
            src: ArchitectureUML.png
            dest: test.jpeg
        - name: Upload image as artifact
          uses: actions/upload-artifact@v1
          with:
            name: png
            path: test.jpeg
