name: diagrams-svg-pfg
on:
  push:
    branches:
      - master

jobs:
  pdf:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Convert test file to png image
          uses: Burnett01/actions-drawio@1.2
          with:
            src: drawio/ArchitectureUML.drawio
            dest: drawio/ArchitectureUML.svg
        - name: Upload image as artifact
          uses: actions/upload-artifact@v1
          with:
            name: svg
            path: drawio/ArchitectureUML.svg
