name: diagrams-svg-pfg
on:
  push:
    branches:
      - master

jobs:
  pdf:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Git clone drawio batch
          run: git clone https://github.com/languitar/drawio-batch.git && \
               cd drawio-batch && \
               apt get install npm
        - name: Upload image as artifact
          uses: actions/upload-artifact@v1
          with:
            name: png
            path: test.jpeg
